### ISSUE TITLE
About performance test

### ISSUE THREAD

**Issue by lyrachord** [xsonorg/xson#1]
Hi brother, great work.
As I known, dsljson is the fastest version in java, maybe tests will include it

**Comment by xsonorg** [comment]
Thank you for your attention :), dsljson is a JSON serialized library, and XSON is a binary serialized library, the two goals are different, so put together is not appropriate, only for reference, like fastjson.

But I still do a simple test:

Test Data:

{"Format":"video/mpg4","Player":"Java","Uri":"http://javaone.com/keynote.mpg","Copyright":"None","Height":480,"Width":640,"Bitrate":"Set: 262144","Title":"Javaone Keynote","Size":58982400}

Test results: CPU preheat after the implementation of 10000 times

XSON ser:29(ms)
XSON length:178
XSON deser :26(ms)

DslJson ser:25(ms)
DslJson length:188
DslJson deser:32(ms)

From the test results point of view, dsljson is a very good serialization library, 
i will be more concerned about him.

**Comment by lyrachord** [comment]
I did a simple measure 100,0000 warm and iteration for dsljson with SOM(my object notation library), the test case shows SOM better than dsljson.
And I did a jmh benchmark to compare, the result of SOM is a little worse than dsljson.
